services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db
  db:
    image: postgres:15.13-alpine3.21
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
volumes:
  postgres_data:
  app_data: